---
name: Bigtop
version: 0.22
author:
  - 'Phil Crow, E<lt>crow.phil@gmail.comE<gt>'
abstract: A web application data language processor
license: perl
requires:
  Config::General: 0
  Gantry: 3.46
  IO::Prompt: 0
  Inline: 0.4
  Inline::TT: 0.06
  Parse::RecDescent: 0
  Template: 2
build_requires:
  Test: 0
  Test::Files: 0
  Test::More: 0
  Test::Warn: 0
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Bigtop:
    file: lib/Bigtop.pm
    version: 0.22
  Bigtop::Backend::CGI:
    file: lib/Bigtop/Backend/CGI.pm
  Bigtop::Backend::CGI::Gantry:
    file: lib/Bigtop/Backend/CGI/Gantry.pm
  Bigtop::Backend::Conf:
    file: lib/Bigtop/Backend/Conf.pm
  Bigtop::Backend::Conf::Gantry:
    file: lib/Bigtop/Backend/Conf/Gantry.pm
  Bigtop::Backend::Conf::General:
    file: lib/Bigtop/Backend/Conf/General.pm
  Bigtop::Backend::Control:
    file: lib/Bigtop/Backend/Control.pm
  Bigtop::Backend::Control::Gantry:
    file: lib/Bigtop/Backend/Control/Gantry.pm
    version: 0.01
  Bigtop::Backend::HttpdConf:
    file: lib/Bigtop/Backend/HttpdConf.pm
  Bigtop::Backend::HttpdConf::Gantry:
    file: lib/Bigtop/Backend/HttpdConf/Gantry.pm
  Bigtop::Backend::Init::Std:
    file: lib/Bigtop/Backend/Init/Std.pm
  Bigtop::Backend::Model:
    file: lib/Bigtop/Backend/Model.pm
  Bigtop::Backend::Model::GantryCDBI:
    file: lib/Bigtop/Backend/Model/GantryCDBI.pm
  Bigtop::Backend::Model::GantryDBIxClass:
    file: lib/Bigtop/Backend/Model/GantryDBIxClass.pm
  Bigtop::Backend::SQL:
    file: lib/Bigtop/Backend/SQL.pm
  Bigtop::Backend::SQL::MySQL:
    file: lib/Bigtop/Backend/SQL/MySQL.pm
  Bigtop::Backend::SQL::Postgres:
    file: lib/Bigtop/Backend/SQL/Postgres.pm
  Bigtop::Backend::SQL::SQLite:
    file: lib/Bigtop/Backend/SQL/SQLite.pm
  Bigtop::Backend::SiteLook::GantryDefault:
    file: lib/Bigtop/Backend/SiteLook/GantryDefault.pm
  Bigtop::Deparser:
    file: lib/Bigtop/Deparser.pm
  Bigtop::Docs::About:
    file: lib/Bigtop/Docs/About.pm
  Bigtop::Docs::Cookbook:
    file: lib/Bigtop/Docs/Cookbook.pm
  Bigtop::Docs::Keywords:
    file: lib/Bigtop/Docs/Keywords.pm
  Bigtop::Docs::Modules:
    file: lib/Bigtop/Docs/Modules.pm
  Bigtop::Docs::QuickRef:
    file: lib/Bigtop/Docs/QuickRef.pm
  Bigtop::Docs::Syntax:
    file: lib/Bigtop/Docs/Syntax.pm
  Bigtop::Docs::TOC:
    file: lib/Bigtop/Docs/TOC.pm
  Bigtop::Docs::TentRef:
    file: lib/Bigtop/Docs/TentRef.pm
  Bigtop::Docs::TentTut:
    file: lib/Bigtop/Docs/TentTut.pm
  Bigtop::Docs::Tutorial:
    file: lib/Bigtop/Docs/Tutorial.pm
  Bigtop::Docs::Vim:
    file: lib/Bigtop/Docs/Vim.pm
  Bigtop::Grammar:
    file: lib/Bigtop/Grammar.pm
  Bigtop::Keywords:
    file: lib/Bigtop/Keywords.pm
  Bigtop::Parser:
    file: lib/Bigtop/Parser.pm
  Bigtop::ScriptHelp:
    file: lib/Bigtop/ScriptHelp.pm
  Bigtop::ScriptHelp::Style:
    file: lib/Bigtop/ScriptHelp/Style.pm
  Bigtop::ScriptHelp::Style::Original:
    file: lib/Bigtop/ScriptHelp/Style/Original.pm
  Bigtop::ScriptHelp::Style::Pg8Live:
    file: lib/Bigtop/ScriptHelp/Style/Pg8Live.pm
  Bigtop::TentMaker:
    file: lib/Bigtop/TentMaker.pm
  Bigtop::TentMakerPath:
    file: lib/Bigtop/TentMakerPath.pm
  Parse::RecDescent::Bigtop::Grammar:
    file: lib/Bigtop/Grammar.pm
resources:
  license: http://dev.perl.org/licenses/
