--- #YAML:1.0
name: Bigtop
version: 0.25
author:
  - Phil Crow, E<lt>crow.phil@gmail.comE<gt>
abstract: A web application data language processor
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
