package Contact::Model::number;
use strict; use warnings;

use base 'Contact::Model::GEN::number', 'Exporter';

our $NUMBER = 'Contact::Model::number';

our @EXPORT_OK = ( '$NUMBER' );

1;

=head1 NAME

Contact::Model::number - model for number table (stub part)

=head1 DESCRIPTION

This model inherits from its generated helper, which inherits from
Gantry::Utils::DBIxClass.  It was generated by Bigtop, but is
NOT subject to regeneration.

=cut
