package Apps::Checkbook::Model::status;
use strict; use warnings;

use base 'Apps::Checkbook::Model::GEN::status', 'Exporter';

our $STATUS = 'Apps::Checkbook::Model::status';

our @EXPORT_OK = ( '$STATUS' );

1;

=head1 NAME

Apps::Checkbook::Model::status - model for status table (stub part)

=head1 DESCRIPTION

This model inherits from its generated helper, which inherits from
Exotic::Base::Module.  It was generated by Bigtop, but is
NOT subject to regeneration.

=cut
