package Apps::Checkbook::Model::trans;
use strict; use warnings;

use base 'Apps::Checkbook::Model::GEN::trans', 'Exporter';

our $TRANS = 'Apps::Checkbook::Model::trans';

our @EXPORT_OK = ( '$TRANS' );

1;

=head1 NAME

Apps::Checkbook::Model::trans - model for trans table (stub part)

=head1 DESCRIPTION

This model inherits from its generated helper, which inherits from
Exotic::Base::Module.  It was generated by Bigtop, but is
NOT subject to regeneration.

=cut
