# NEVER EDIT this file.  It was generated and will be overwritten without
# notice upon regeneration of this application.  You have been warned.
package GENSample;

use strict;

use Gantry qw{ -TemplateEngine=TT };

our @ISA = qw( Gantry );


##-----------------------------------------------------------------
## $self->init( $r )
##-----------------------------------------------------------------
#sub init {
#    my ( $self, $r ) = @_;
#
#    # process SUPER's init code
#    $self->SUPER::init( $r );
#
#} # END init


use Sample::Model::tbl1 qw(
    $TBL1
);
use Gantry::Plugins::NewOne;


use Missing::Module;



#-----------------------------------------------------------------
# $self->do_main(  )
#-----------------------------------------------------------------
sub do_main {
    my ( $self ) = @_;

    $self->stash->view->template( 'results.tt' );
    $self->stash->view->title( 'Sample' );

    my $real_location = $self->location() || '';
    if ( $real_location ) {
        $real_location =~ s{/+$}{};
        $real_location .= '/';
    }

    my $retval = {
        headings       => [
            'Name',
            'Phone',
        ],
        header_options => [
            {
                text => 'Add',
                link => $real_location . "add",
            },
        ],
    };

    my $schema = $self->get_schema();
    my @rows   = $TBL1->get_listing( { schema => $schema } );

    foreach my $row ( @rows ) {
        my $id = $row->id;
        push(
            @{ $retval->{rows} }, {
                data => [
                    $row->name,
                    $row->phone,
                ],
                options => [
                    {
                        text => 'Edit',
                        link => $real_location . "edit/$id",
                    },
                    {
                        text => 'Delete',
                        link => $real_location . "delete/$id",
                    },
                ],
            }
        );
    }

    $self->stash->view->data( $retval );
} # END do_main

#-----------------------------------------------------------------
# $self->form( $row )
#-----------------------------------------------------------------
sub form {
    my ( $self, $row ) = @_;

    my $selections = $TBL1->get_form_selections(
            { schema => $self->get_schema() }
    );

    return {
        row        => $row,
        fields     => [
            {
                name => 'name',
                label => 'Name',
                is => 'varchar',
            },
            {
                name => 'phone',
                label => 'Phone',
                is => 'varchar',
            },
        ],
    };
} # END form

1;

=head1 NAME

GENSample - generated support module for Sample

=head1 SYNOPSIS

In Sample:

    use base 'GENSample';

=head1 DESCRIPTION

This module was generated by Bigtop (and IS subject to regeneration) to
provide methods in support of the whole Sample
application.

Sample should inherit from this module.

=head1 METHODS

=over 4

=item init

=item do_main

=item form


=back

=head1 AUTHOR

SomeOne

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2006 SomeOne

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.8.6 or,
at your option, any later version of Perl 5 you may have available.

=cut

